// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlL8Ve_PTUlJZ0IW5EwKeDhax0B8CIjh0',
    appId: '1:442445961131:android:40d1720334b72ff10ee4ee',
    messagingSenderId: '442445961131',
    projectId: 'review-provider-sqlite',
    storageBucket: 'review-provider-sqlite.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNmnzY907bLLtc_oxgMomt-_BXAEn9EBI',
    appId: '1:442445961131:ios:dba65baa51abbdb70ee4ee',
    messagingSenderId: '442445961131',
    projectId: 'review-provider-sqlite',
    storageBucket: 'review-provider-sqlite.appspot.com',
    androidClientId: '442445961131-jvg99h0o0m4sa1mbvunr34c8551pq0ak.apps.googleusercontent.com',
    iosClientId: '442445961131-36llvrq14lvi8u439tb4kbmn4v0fnibv.apps.googleusercontent.com',
    iosBundleId: 'br.com.novelitech.reviewProviderSqlite',
  );

}