name: Push To Main Branch

on:
    push:
        branches: ["main"]
    
    workflow_dispatch:
    
jobs:
    build:
        name: Build App
        runs-on: ubuntu-latest
        permissions: read-all
        steps:
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0  
            
            - uses: actions/setup-java@v4
              with:
                distribution: 'zulu'
                java-version: 17.x
                cache: 'gradle'
        
            - uses: subosito/flutter-action@v2
              with:
                flutter-version: 3.24.3
                channel: 'stable'
                cache: true
        
            - name: Get dependencies
              run: flutter pub get
        
            - name: Flutter Analize
              run: flutter analyze
        
            - name: Run Flutter Test
              run: flutter test